# Generated by Django 4.2.7 on 2023-11-09 02:10

import asoron.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='img_url',
            field=models.ImageField(upload_to='store/images', validators=[asoron.validators.validate_file_size]),
        ),
    ]
