# Generated by Django 4.2.7 on 2023-11-09 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0002_alter_imagen_img_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoDestilacion',
            fields=[
                ('meto_dest_id', models.AutoField(primary_key=True, serialize=False)),
                ('meto_dest_nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MetodoFermentacion',
            fields=[
                ('meto_ferm_id', models.AutoField(primary_key=True, serialize=False)),
                ('meto_ferm_nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Anejamiento',
            fields=[
                ('anej_id', models.AutoField(primary_key=True, serialize=False)),
                ('anej_cantidad_anos', models.PositiveIntegerField()),
                ('anej_calidad_agua', models.CharField(choices=[('Buena', 'Buena'), ('Regular', 'Regular'), ('Mala', 'Mala')], max_length=10)),
                ('fk_anej_meto_dest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asoron.metododestilacion')),
                ('fk_anej_meto_ferm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asoron.metodofermentacion')),
            ],
        ),
    ]
