# Generated by Django 4.2.7 on 2023-11-09 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0003_metododestilacion_metodofermentacion_anejamiento'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='anejamiento',
            constraint=models.CheckConstraint(check=models.Q(('anej_calidad_agua__in', ['A', 'n', 'e', 'j', 'a', 'm', 'i', 'e', 'n', 't', 'o', '.', 'C', 'A', 'L', 'I', 'D', 'A', 'D', '_', 'A', 'G', 'U', 'A'])), name='calidad_agua_check'),
        ),
    ]
