# Generated by Django 4.2.7 on 2023-11-09 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0004_anejamiento_calidad_agua_check'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='anejamiento',
            name='calidad_agua_check',
        ),
    ]
