# Generated by Django 4.2.7 on 2023-11-09 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0006_ron_fk_ron_anej_alter_anejamiento_fk_anej_meto_dest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ron',
            name='fk_ron_anej',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ron_anejamiento', to='asoron.anejamiento'),
        ),
    ]
