# Generated by Django 4.2.7 on 2023-11-09 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0007_alter_ron_fk_ron_anej'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barril',
            fields=[
                ('barr_id', models.AutoField(primary_key=True, serialize=False)),
                ('barr_calidad', models.CharField(choices=[('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Malo', 'Malo')], max_length=50)),
                ('barr_tipo', models.CharField(choices=[('Bourbon', 'Bourbon')], max_length=50)),
                ('barr_tamano', models.PositiveIntegerField()),
                ('barr_tipo_madera', models.CharField(choices=[('Roble', 'Roble')], max_length=50)),
            ],
        ),
    ]
