# Generated by Django 4.2.7 on 2023-11-09 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0008_barril'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarrilAnejamiento',
            fields=[
                ('barr_anej_id', models.AutoField(primary_key=True, serialize=False)),
                ('barr_anej_anos_barril', models.PositiveIntegerField()),
                ('fk_barr_anej_anej', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barr_anej_anej', to='asoron.anejamiento')),
                ('fk_barr_anej_barr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barr_anej_barr', to='asoron.barril')),
            ],
            options={
                'unique_together': {('fk_barr_anej_anej', 'fk_barr_anej_barr')},
            },
        ),
    ]
