# Generated by Django 4.2.7 on 2023-11-10 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0010_color_gradoalcohol_sensacion_sensacionron'),
    ]

    operations = [
        migrations.AddField(
            model_name='ron',
            name='fk_ron_color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ron_color', to='asoron.color'),
        ),
        migrations.AddField(
            model_name='ron',
            name='fk_ron_grado_alco',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='ron_grado_alcohol', to='asoron.gradoalcohol'),
        ),
    ]
