# Generated by Django 4.2.7 on 2023-11-10 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0011_ron_fk_ron_color_ron_fk_ron_grado_alco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensacionron',
            name='fk_sens_ron_ron',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sens_ron_ron', to='asoron.ron'),
        ),
    ]
