# Generated by Django 4.2.7 on 2023-11-10 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0013_materiaprima_materiaprimaron'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='empl_apellido',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='empl_cedula_identidad',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='empl_nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
