# Generated by Django 4.2.7 on 2023-11-10 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0014_empleado_empl_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='empl_apellido',
            field=models.CharField(default='cambiar', max_length=50),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='empl_cedula_identidad',
            field=models.CharField(default='cambiar', max_length=10),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='empl_nombre',
            field=models.CharField(default='cambiar', max_length=50),
        ),
    ]
