# Generated by Django 4.2.7 on 2023-11-11 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0016_alter_empleado_empl_apellido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('prov_id', models.AutoField(primary_key=True, serialize=False)),
                ('prov_rif', models.CharField(max_length=10)),
                ('prov_denominacion_comercial', models.CharField(max_length=50)),
                ('prov_razon_social', models.CharField(max_length=50)),
                ('prov_pagina_web', models.CharField(blank=True, max_length=50, null=True)),
                ('prov_direccion_fiscal', models.CharField(max_length=200)),
                ('prov_direccion_fisica', models.CharField(max_length=200)),
            ],
        ),
    ]
