# Generated by Django 4.2.7 on 2023-11-11 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0017_proveedor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name_plural': 'Proveedor'},
        ),
    ]
