# Generated by Django 4.2.7 on 2023-11-11 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0018_alter_proveedor_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ron',
            name='fk_ron_prove',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ron_proveedor', to='asoron.proveedor'),
        ),
    ]
