# Generated by Django 4.2.7 on 2023-11-11 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0019_ron_fk_ron_prove'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ron',
            options={'verbose_name_plural': 'Ron'},
        ),
    ]
