# Generated by Django 4.2.7 on 2023-11-11 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0020_alter_ron_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anejamiento',
            options={'verbose_name_plural': 'Añejamiento'},
        ),
        migrations.AlterModelOptions(
            name='barril',
            options={'verbose_name_plural': 'Barril'},
        ),
        migrations.AlterModelOptions(
            name='barrilanejamiento',
            options={'verbose_name_plural': 'Barril y Añejamiento'},
        ),
        migrations.AlterModelOptions(
            name='clasificacionron',
            options={'verbose_name_plural': 'Clasificacion Ron'},
        ),
        migrations.AlterModelOptions(
            name='clasificaciontipo',
            options={'verbose_name_plural': 'Clasificacion y Tipo'},
        ),
        migrations.AlterModelOptions(
            name='clientejuridico',
            options={'verbose_name_plural': 'Cliente Juridico'},
        ),
        migrations.AlterModelOptions(
            name='clientenatural',
            options={'verbose_name_plural': 'Cliente Natural'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name_plural': 'Color'},
        ),
        migrations.AlterModelOptions(
            name='departamento',
            options={'verbose_name_plural': 'Departamento'},
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'verbose_name_plural': 'Empleado'},
        ),
        migrations.AlterModelOptions(
            name='gradoalcohol',
            options={'verbose_name_plural': 'Grado Alcohol'},
        ),
        migrations.AlterModelOptions(
            name='imagen',
            options={'verbose_name_plural': 'Imagen'},
        ),
        migrations.AlterModelOptions(
            name='materiaprima',
            options={'verbose_name_plural': 'Materia Prima'},
        ),
        migrations.AlterModelOptions(
            name='materiaprimaron',
            options={'verbose_name_plural': 'Materia Prima del Ron'},
        ),
        migrations.AlterModelOptions(
            name='metododestilacion',
            options={'verbose_name_plural': 'Metodo Destilacion'},
        ),
        migrations.AlterModelOptions(
            name='metodofermentacion',
            options={'verbose_name_plural': 'Metodo Fermentacion'},
        ),
        migrations.AlterModelOptions(
            name='sensacion',
            options={'verbose_name_plural': 'Sensacion'},
        ),
        migrations.AlterModelOptions(
            name='sensacionron',
            options={'verbose_name_plural': 'Sensacion del Ron'},
        ),
        migrations.AlterModelOptions(
            name='telefono',
            options={'verbose_name_plural': 'Telefono'},
        ),
        migrations.AlterModelOptions(
            name='telefonocodigo',
            options={'verbose_name_plural': 'Codigo de Telefono'},
        ),
        migrations.AlterModelOptions(
            name='tipocomercio',
            options={'verbose_name_plural': 'Tipo de Comercio'},
        ),
        migrations.AlterModelOptions(
            name='tiporon',
            options={'verbose_name_plural': 'Tipo Ron'},
        ),
        migrations.AlterUniqueTogether(
            name='barrilanejamiento',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='clasificaciontipo',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='materiaprimaron',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='sensacionron',
            unique_together=set(),
        ),
    ]
