# Generated by Django 4.2.7 on 2023-11-11 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0021_alter_anejamiento_options_alter_barril_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='barrilanejamiento',
            unique_together={('fk_barr_anej_anej', 'fk_barr_anej_barr')},
        ),
        migrations.AlterUniqueTogether(
            name='clasificaciontipo',
            unique_together={('fk_clasi_tipo_clasi_ron', 'fk_clasi_tipo_tipo_ron')},
        ),
        migrations.AlterUniqueTogether(
            name='materiaprimaron',
            unique_together={('fk_mate_prima_ron_mate_prima', 'fk_mate_prima_ron_ron')},
        ),
        migrations.AlterUniqueTogether(
            name='sensacionron',
            unique_together={('fk_sens_ron_sens', 'fk_sens_ron_ron')},
        ),
    ]
