# Generated by Django 4.2.7 on 2023-11-11 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0022_alter_barrilanejamiento_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('lugar_id', models.AutoField(primary_key=True, serialize=False)),
                ('lugar_tipo', models.CharField(choices=[('Estado', 'Estado'), ('Parroquia', 'Parroquia'), ('Pais', 'Pais')], max_length=50)),
                ('lugar_nombre', models.CharField(max_length=50)),
                ('fk_lugar_lugar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asoron.lugar')),
            ],
        ),
    ]
