# Generated by Django 4.2.7 on 2023-11-11 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0023_lugar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lugar',
            options={'verbose_name_plural': 'Lugar'},
        ),
    ]
