# Generated by Django 4.2.7 on 2023-11-11 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0024_alter_lugar_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ron',
            name='fk_ron_lugar',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='ron_lugar', to='asoron.lugar'),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='lugar_tipo',
            field=models.CharField(choices=[('Pais', 'Pais'), ('Estado', 'Estado'), ('Parroquia', 'Parroquia')], max_length=50),
        ),
    ]
