# Generated by Django 4.2.7 on 2023-11-13 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0031_comoservir_comoservirron'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comoservir',
            options={'verbose_name_plural': 'Como Servir'},
        ),
    ]
