# Generated by Django 4.2.7 on 2023-11-13 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0032_alter_comoservir_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prueba',
        ),
    ]
