# Generated by Django 4.2.7 on 2023-11-13 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0033_delete_prueba'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('mate_id', models.AutoField(primary_key=True, serialize=False)),
                ('mate_nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Material',
            },
        ),
        migrations.CreateModel(
            name='Tapa',
            fields=[
                ('tapa_id', models.AutoField(primary_key=True, serialize=False)),
                ('tapa_nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Tapa',
            },
        ),
        migrations.CreateModel(
            name='TipoBotella',
            fields=[
                ('tipo_bote_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_bote_altura', models.PositiveIntegerField()),
                ('tipo_bote_ancho', models.PositiveIntegerField()),
                ('tipo_bote_capacidad', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Tipo Botella',
            },
        ),
        migrations.CreateModel(
            name='TapaMaterial',
            fields=[
                ('tapa_mate_id', models.AutoField(primary_key=True, serialize=False)),
                ('fk_tapa_mate_mate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asoron.material')),
                ('fk_tapa_mate_tapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asoron.tapa')),
            ],
            options={
                'verbose_name_plural': 'Tapa y Material',
                'unique_together': {('fk_tapa_mate_tapa', 'fk_tapa_mate_mate')},
            },
        ),
        migrations.CreateModel(
            name='MaterialTipoBotella',
            fields=[
                ('mate_tipo_bote_id', models.AutoField(primary_key=True, serialize=False)),
                ('mate_tipo_bote_peso', models.PositiveIntegerField()),
                ('fk_mate_tipo_bote_mate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asoron.material')),
                ('fk_mate_tipo_bote_tipo_bote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asoron.tipobotella')),
            ],
            options={
                'verbose_name_plural': 'Material y Tipo Botella',
                'unique_together': {('fk_mate_tipo_bote_mate', 'fk_mate_tipo_bote_tipo_bote')},
            },
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('caja_id', models.AutoField(primary_key=True, serialize=False)),
                ('caja_cantidad', models.PositiveIntegerField()),
                ('caja_tipo', models.CharField(choices=[('Paleta', 'Paleta'), ('Bulto', 'Bulto'), ('Caja', 'Caja')], max_length=50)),
                ('caja_nombre', models.CharField(max_length=50)),
                ('fk_caja_caja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asoron.caja')),
            ],
            options={
                'verbose_name_plural': 'Caja',
            },
        ),
        migrations.CreateModel(
            name='Botella',
            fields=[
                ('bote_id', models.AutoField(primary_key=True, serialize=False)),
                ('bote_nombre', models.CharField(max_length=50)),
                ('bote_descripcion', models.CharField(max_length=200)),
                ('fk_bote_caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bote_caja', to='asoron.caja')),
                ('fk_bote_mate_tipo_bote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bote_mate_tipo_bote', to='asoron.materialtipobotella')),
                ('fk_bote_ron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bote_ron', to='asoron.ron')),
                ('fk_bote_tapa_mate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bote_tapa_mate', to='asoron.tapamaterial')),
            ],
            options={
                'verbose_name_plural': 'Botella',
            },
        ),
    ]
