# Generated by Django 4.2.7 on 2023-11-13 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0034_material_tapa_tipobotella_tapamaterial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorreoElectronico',
            fields=[
                ('mail_id', models.AutoField(primary_key=True, serialize=False)),
                ('mail_dirrecion_correo', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
