# Generated by Django 4.2.7 on 2023-11-13 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0037_alter_correoelectronico_fk_mail_prov'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='correoelectronico',
            options={'verbose_name_plural': 'Correo Electronico'},
        ),
    ]
