# Generated by Django 4.2.7 on 2023-11-13 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0038_alter_correoelectronico_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='telefono',
            name='fk_telf_empl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empl_telf', to='asoron.empleado'),
        ),
        migrations.AddField(
            model_name='telefono',
            name='fk_telf_prov',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prov_telf', to='asoron.proveedor'),
        ),
    ]
