# Generated by Django 4.2.7 on 2023-11-13 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0039_telefono_fk_telf_empl_telefono_fk_telf_prov'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botella',
            name='bote_descripcion',
            field=models.CharField(max_length=200, verbose_name='Descripcion de la botella'),
        ),
        migrations.AlterField(
            model_name='botella',
            name='bote_nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre de la botella'),
        ),
        migrations.AlterField(
            model_name='botella',
            name='fk_bote_caja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bote_caja', to='asoron.caja', verbose_name='Caja'),
        ),
        migrations.AlterField(
            model_name='botella',
            name='fk_bote_mate_tipo_bote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bote_mate_tipo_bote', to='asoron.materialtipobotella', verbose_name='Material y Tipo Botella'),
        ),
        migrations.AlterField(
            model_name='botella',
            name='fk_bote_tapa_mate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bote_tapa_mate', to='asoron.tapamaterial', verbose_name='Tapa y Material'),
        ),
        migrations.AlterField(
            model_name='comoservirron',
            name='como_serv_ron_descripcion',
            field=models.CharField(max_length=200, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='comoservirron',
            name='fk_como_serv_ron_como_serv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asoron.comoservir', verbose_name='Coctel'),
        ),
        migrations.AlterField(
            model_name='materiaprimaron',
            name='fk_mate_prima_ron_mate_prima',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asoron.materiaprima', verbose_name='Materia Prima del Ron'),
        ),
        migrations.AlterField(
            model_name='sensacionron',
            name='fk_sens_ron_sens',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asoron.sensacion', verbose_name='Sensacion del ron'),
        ),
    ]
