# Generated by Django 4.2.7 on 2023-11-13 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0040_alter_botella_bote_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barrilanejamiento',
            name='barr_anej_anos_barril',
            field=models.PositiveIntegerField(verbose_name='Años del barril'),
        ),
        migrations.AlterField(
            model_name='barrilanejamiento',
            name='fk_barr_anej_barr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barr_anej_barr', to='asoron.barril', verbose_name='Barril'),
        ),
    ]
