# Generated by Django 4.2.7 on 2023-11-13 20:04

import asoron.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0042_alter_telefono_fk_telf_telf_codi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anejamiento',
            name='anej_calidad_agua',
            field=models.CharField(choices=[('Buena', 'Buena'), ('Regular', 'Regular'), ('Mala', 'Mala')], max_length=10, verbose_name='Calidad del agua'),
        ),
        migrations.AlterField(
            model_name='anejamiento',
            name='anej_cantidad_anos',
            field=models.PositiveIntegerField(verbose_name='Cantidad de años'),
        ),
        migrations.AlterField(
            model_name='anejamiento',
            name='anej_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='identificador'),
        ),
        migrations.AlterField(
            model_name='anejamiento',
            name='fk_anej_meto_dest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anej_meto_dest', to='asoron.metododestilacion', verbose_name='Metodo de destilacion'),
        ),
        migrations.AlterField(
            model_name='anejamiento',
            name='fk_anej_meto_ferm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anej_meto_ferm', to='asoron.metodofermentacion', verbose_name='Metodo de fermentacion'),
        ),
        migrations.AlterField(
            model_name='barril',
            name='barr_calidad',
            field=models.CharField(choices=[('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Malo', 'Malo')], max_length=50, verbose_name='Calidad del barril'),
        ),
        migrations.AlterField(
            model_name='barril',
            name='barr_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='identificador'),
        ),
        migrations.AlterField(
            model_name='barril',
            name='barr_tamano',
            field=models.PositiveIntegerField(verbose_name='Tamaño del barril'),
        ),
        migrations.AlterField(
            model_name='barril',
            name='barr_tipo',
            field=models.CharField(choices=[('Bourbon', 'Bourbon')], max_length=50, verbose_name='Tipo de barril'),
        ),
        migrations.AlterField(
            model_name='barril',
            name='barr_tipo_madera',
            field=models.CharField(choices=[('Roble', 'Roble')], max_length=50, verbose_name='Tipo de madera'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='caja_cantidad',
            field=models.PositiveIntegerField(verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='caja_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='identificador'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='caja_nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='caja_tipo',
            field=models.CharField(choices=[('Paleta', 'Paleta'), ('Bulto', 'Bulto'), ('Caja', 'Caja')], max_length=50, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='fk_caja_caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asoron.caja', verbose_name='Embalaje'),
        ),
        migrations.AlterField(
            model_name='clasificacionron',
            name='clasi_ron_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='identificador'),
        ),
        migrations.AlterField(
            model_name='clasificacionron',
            name='clasi_ron_nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='clasificaciontipo',
            name='clasi_tipo_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='identificador'),
        ),
        migrations.AlterField(
            model_name='clasificaciontipo',
            name='fk_clasi_tipo_clasi_ron',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clasi_tipo_ron', to='asoron.clasificacionron', verbose_name='Clasificacion Ron'),
        ),
        migrations.AlterField(
            model_name='clasificaciontipo',
            name='fk_clasi_tipo_tipo_ron',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clasi_tipo_ron', to='asoron.tiporon', verbose_name='Tipo Ron'),
        ),
        migrations.AlterField(
            model_name='clientejuridico',
            name='clie_juri_capital_disponible',
            field=models.PositiveIntegerField(default=0, verbose_name='Capital Disponible'),
        ),
        migrations.AlterField(
            model_name='clientejuridico',
            name='clie_juri_denominacion_comercial',
            field=models.CharField(max_length=50, verbose_name='Denominacion Comercial'),
        ),
        migrations.AlterField(
            model_name='clientejuridico',
            name='clie_juri_direccion_fiscal',
            field=models.CharField(max_length=200, verbose_name='Direccion Fiscal'),
        ),
        migrations.AlterField(
            model_name='clientejuridico',
            name='clie_juri_direccion_fisica',
            field=models.CharField(max_length=200, verbose_name='Direccion Fisica'),
        ),
        migrations.AlterField(
            model_name='clientejuridico',
            name='clie_juri_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='identificador'),
        ),
        migrations.AlterField(
            model_name='clientejuridico',
            name='clie_juri_pagina_web',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Pagina Web'),
        ),
        migrations.AlterField(
            model_name='clientejuridico',
            name='clie_juri_puntos',
            field=models.PositiveIntegerField(default=0, verbose_name='Puntos'),
        ),
        migrations.AlterField(
            model_name='clientejuridico',
            name='clie_juri_razon_social',
            field=models.CharField(max_length=50, verbose_name='Razon Social'),
        ),
        migrations.AlterField(
            model_name='clientejuridico',
            name='clie_juri_rif',
            field=models.CharField(max_length=10, verbose_name='RIF'),
        ),
        migrations.AlterField(
            model_name='clientejuridico',
            name='fk_clie_juri_lugar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asoron.lugar', verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='clientejuridico',
            name='fk_clie_juri_tipo_come',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asoron.tipocomercio', verbose_name='Tipo de Comercio'),
        ),
        migrations.AlterField(
            model_name='clientenatural',
            name='clie_natu_apellido',
            field=models.CharField(max_length=50, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='clientenatural',
            name='clie_natu_cedula_identidad',
            field=models.CharField(max_length=10, verbose_name='Cedula de identidad'),
        ),
        migrations.AlterField(
            model_name='clientenatural',
            name='clie_natu_direccion_habitacion',
            field=models.CharField(max_length=200, verbose_name='Direccion de habitacion'),
        ),
        migrations.AlterField(
            model_name='clientenatural',
            name='clie_natu_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='identificador'),
        ),
        migrations.AlterField(
            model_name='clientenatural',
            name='clie_natu_nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='clientenatural',
            name='clie_natu_puntos',
            field=models.PositiveIntegerField(default=0, verbose_name='Puntos'),
        ),
        migrations.AlterField(
            model_name='clientenatural',
            name='clie_natu_rif',
            field=models.CharField(max_length=10, verbose_name='RIF'),
        ),
        migrations.AlterField(
            model_name='clientenatural',
            name='clie_natu_segundo_apellido',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Segundo Apellido'),
        ),
        migrations.AlterField(
            model_name='clientenatural',
            name='clie_natu_segundo_nombre',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Segundo Nombre'),
        ),
        migrations.AlterField(
            model_name='clientenatural',
            name='fk_clie_natu_lugar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asoron.lugar', verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='color',
            name='color_descripcion',
            field=models.CharField(max_length=200, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='color',
            name='color_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='identificador'),
        ),
        migrations.AlterField(
            model_name='color',
            name='color_nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='comoservir',
            name='como_serv_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='identificador'),
        ),
        migrations.AlterField(
            model_name='comoservir',
            name='como_serv_nombre',
            field=models.CharField(max_length=50, verbose_name='Coctel'),
        ),
        migrations.AlterField(
            model_name='correoelectronico',
            name='mail_dirrecion_correo',
            field=models.CharField(max_length=50, unique=True, verbose_name='Direccion de correo electronico'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='depa_descripcion',
            field=models.CharField(max_length=200, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='depa_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='identificador'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='depa_nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='empl_apellido',
            field=models.CharField(max_length=50, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='empl_cedula_identidad',
            field=models.CharField(max_length=10, verbose_name='Cedula de identidad'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='empl_direccion',
            field=models.CharField(max_length=200, verbose_name='Direccion Fisica'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='empl_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='identificador'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='empl_nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fk_empl_depa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asoron.departamento', verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fk_empl_lugar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asoron.lugar', verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='gradoalcohol',
            name='grad_alco_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='identificador'),
        ),
        migrations.AlterField(
            model_name='gradoalcohol',
            name='grad_alco_porcentaje_alcohol',
            field=models.PositiveIntegerField(verbose_name='Grado de alcohol'),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='img_url',
            field=models.ImageField(upload_to='store/images', validators=[asoron.validators.validate_file_size], verbose_name='Imagen URL'),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='fk_lugar_lugar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asoron.lugar', verbose_name='Lugar Origen'),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='lugar_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='identificador'),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='lugar_nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre del lugar'),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='lugar_tipo',
            field=models.CharField(choices=[('Pais', 'Pais'), ('Estado', 'Estado'), ('Parroquia', 'Parroquia')], max_length=50, verbose_name='Tipo de lugar'),
        ),
        migrations.AlterField(
            model_name='material',
            name='mate_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='identificador'),
        ),
        migrations.AlterField(
            model_name='material',
            name='mate_nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='materialtipobotella',
            name='fk_mate_tipo_bote_mate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asoron.material', verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='materialtipobotella',
            name='fk_mate_tipo_bote_tipo_bote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asoron.tipobotella', verbose_name='Tipo de Botella'),
        ),
        migrations.AlterField(
            model_name='materialtipobotella',
            name='mate_tipo_bote_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='identificador'),
        ),
        migrations.AlterField(
            model_name='materialtipobotella',
            name='mate_tipo_bote_peso',
            field=models.PositiveIntegerField(verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='mate_prima_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='identificador'),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='mate_prima_nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='metododestilacion',
            name='meto_dest_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='identificador'),
        ),
        migrations.AlterField(
            model_name='metododestilacion',
            name='meto_dest_nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='metodofermentacion',
            name='meto_ferm_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='identificador'),
        ),
        migrations.AlterField(
            model_name='metodofermentacion',
            name='meto_ferm_nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='fk_prov_lugar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asoron.lugar', verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='prov_denominacion_comercial',
            field=models.CharField(max_length=50, verbose_name='Denominacion Comercial'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='prov_direccion_fiscal',
            field=models.CharField(max_length=200, verbose_name='Direccion Fiscal'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='prov_direccion_fisica',
            field=models.CharField(max_length=200, verbose_name='Direccion Fisica'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='prov_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='identificador'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='prov_pagina_web',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Pagina Web'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='prov_razon_social',
            field=models.CharField(max_length=50, verbose_name='Razon Social'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='prov_rif',
            field=models.CharField(max_length=10, verbose_name='RIF'),
        ),
        migrations.AlterField(
            model_name='ron',
            name='fk_ron_anej',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ron_anejamiento', to='asoron.anejamiento', verbose_name='Añejamiento'),
        ),
        migrations.AlterField(
            model_name='ron',
            name='fk_ron_clasi_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asoron.clasificaciontipo', verbose_name='Clasificacion y Tipo'),
        ),
        migrations.AlterField(
            model_name='ron',
            name='fk_ron_color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ron_color', to='asoron.color', verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='ron',
            name='fk_ron_grado_alco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ron_grado_alcohol', to='asoron.gradoalcohol', verbose_name='Grado Alcohol'),
        ),
        migrations.AlterField(
            model_name='ron',
            name='fk_ron_lugar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ron_lugar', to='asoron.lugar', verbose_name='Origen'),
        ),
        migrations.AlterField(
            model_name='ron',
            name='fk_ron_prove',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ron_proveedor', to='asoron.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='ron',
            name='ron_descripcion',
            field=models.CharField(max_length=200, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='ron',
            name='ron_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='identificador'),
        ),
        migrations.AlterField(
            model_name='ron',
            name='ron_nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='sensacion',
            name='sens_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='identificador'),
        ),
        migrations.AlterField(
            model_name='sensacion',
            name='sens_nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='tapa',
            name='tapa_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='identificador'),
        ),
        migrations.AlterField(
            model_name='tapa',
            name='tapa_nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='tapamaterial',
            name='fk_tapa_mate_mate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asoron.material', verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='tapamaterial',
            name='fk_tapa_mate_tapa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asoron.tapa', verbose_name='Tapa'),
        ),
        migrations.AlterField(
            model_name='tapamaterial',
            name='tapa_mate_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='identificador'),
        ),
        migrations.AlterField(
            model_name='telefonocodigo',
            name='telf_cod_codigo',
            field=models.CharField(max_length=4, verbose_name='Codigo de area'),
        ),
        migrations.AlterField(
            model_name='telefonocodigo',
            name='telf_cod_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='identificador'),
        ),
        migrations.AlterField(
            model_name='tipobotella',
            name='tipo_bote_altura',
            field=models.PositiveIntegerField(verbose_name='Altura'),
        ),
        migrations.AlterField(
            model_name='tipobotella',
            name='tipo_bote_ancho',
            field=models.PositiveIntegerField(verbose_name='Ancho'),
        ),
        migrations.AlterField(
            model_name='tipobotella',
            name='tipo_bote_capacidad',
            field=models.PositiveIntegerField(verbose_name='Capacidad'),
        ),
        migrations.AlterField(
            model_name='tipobotella',
            name='tipo_bote_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='identificador'),
        ),
        migrations.AlterField(
            model_name='tipocomercio',
            name='tipo_comer_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='identificador'),
        ),
        migrations.AlterField(
            model_name='tipocomercio',
            name='tipo_comer_nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='tiporon',
            name='tipo_ron_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='identificador'),
        ),
        migrations.AlterField(
            model_name='tiporon',
            name='tipo_ron_nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
    ]
