# Generated by Django 4.2.7 on 2023-11-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0043_alter_anejamiento_anej_calidad_agua_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='lugar_tipo',
            field=models.CharField(choices=[('Municipio', 'Municipio'), ('Estado', 'Estado'), ('Parroquia', 'Parroquia')], max_length=50, verbose_name='Tipo de lugar'),
        ),
    ]
