# Generated by Django 4.2.7 on 2023-11-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0044_alter_lugar_lugar_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barril',
            name='barr_tipo',
            field=models.CharField(max_length=50, verbose_name='Tipo de barril'),
        ),
    ]
