# Generated by Django 4.2.7 on 2023-11-13 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0045_alter_barril_barr_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='fk_empl_lugar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asoron.lugar', verbose_name='Direccion'),
        ),
    ]
