# Generated by Django 4.2.7 on 2023-11-20 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0048_alter_clasificaciontipo_fk_clasi_tipo_tipo_ron'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('asis_id', models.AutoField(primary_key=True, serialize=False, verbose_name='identificador')),
                ('asis_hora_entrada', models.TimeField(verbose_name='Hora de entrada')),
                ('asis_hora_salida', models.TimeField(verbose_name='Hora de salida')),
            ],
            options={
                'verbose_name_plural': 'Asistencia',
            },
        ),
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('bene_id', models.AutoField(primary_key=True, serialize=False, verbose_name='identificador')),
                ('bene_nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('bene_descripcion', models.CharField(max_length=200, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name_plural': 'Beneficio',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('hora_id', models.AutoField(primary_key=True, serialize=False, verbose_name='identificador')),
                ('hora_hora_entrada', models.TimeField(verbose_name='Hora de entrada')),
                ('hora_hora_salida', models.TimeField(verbose_name='Hora de salida')),
                ('hora_dia', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miercoles', 'Miercoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sabado', 'Sabado'), ('Domingo', 'Domingo')], max_length=50, verbose_name='Dia')),
            ],
            options={
                'verbose_name_plural': 'Horario',
            },
        ),
        migrations.CreateModel(
            name='Salario',
            fields=[
                ('sala_id', models.AutoField(primary_key=True, serialize=False, verbose_name='identificador')),
                ('sala_sueldo', models.PositiveIntegerField(verbose_name='Sueldo')),
            ],
            options={
                'verbose_name_plural': 'Salario',
            },
        ),
        migrations.CreateModel(
            name='Vacacion',
            fields=[
                ('vaca_id', models.AutoField(primary_key=True, serialize=False, verbose_name='identificador')),
                ('vaca_fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('vaca_fecha_fin', models.DateField(verbose_name='Fecha de fin')),
            ],
            options={
                'verbose_name_plural': 'Vacacion',
            },
        ),
        migrations.AlterModelOptions(
            name='clasificaciontipo',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='clasificaciontipo',
            unique_together=set(),
        ),
    ]
