# Generated by Django 4.2.7 on 2023-11-20 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0051_alter_empleado_fk_empl_vaca'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalarioEmpleado',
            fields=[
                ('sala_empl_id', models.AutoField(primary_key=True, serialize=False)),
                ('sala_empl_fecha_incio', models.DateField(verbose_name='Fecha de inicio')),
                ('sala_empl_fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('fk_sala_empl_empl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asoron.empleado', verbose_name='Empleado')),
                ('fk_sala_empl_sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asoron.salario', verbose_name='Salario')),
            ],
        ),
        migrations.CreateModel(
            name='HorarioEmpleado',
            fields=[
                ('hora_empl_id', models.AutoField(primary_key=True, serialize=False)),
                ('hora_empl_fecha_incio', models.DateField(verbose_name='Fecha de inicio')),
                ('hora_empl_fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('fk_hora_empl_empl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asoron.empleado', verbose_name='Empleado')),
                ('fk_hora_empl_hora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asoron.horario', verbose_name='Horario')),
            ],
        ),
        migrations.CreateModel(
            name='BeneficioEmpleado',
            fields=[
                ('bene_empl_id', models.AutoField(primary_key=True, serialize=False)),
                ('bene_empl_fecha_incio', models.DateField(verbose_name='Fecha de inicio')),
                ('bene_empl_fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('fk_bene_empl_bene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asoron.beneficio', verbose_name='Beneficio')),
                ('fk_bene_empl_empl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asoron.empleado', verbose_name='Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='AsistenciaEmpleado',
            fields=[
                ('asis_empl_id', models.AutoField(primary_key=True, serialize=False)),
                ('asis_empl_fecha_asistencia', models.DateField(verbose_name='Fecha de asistencia')),
                ('fk_asis_empl_asis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asoron.asistencia', verbose_name='Asistencia')),
                ('fk_asis_empl_empl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asoron.empleado', verbose_name='Empleado')),
            ],
        ),
    ]
