# Generated by Django 4.2.7 on 2023-11-20 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0052_salarioempleado_horarioempleado_beneficioempleado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('noti_id', models.AutoField(primary_key=True, serialize=False, verbose_name='identificador')),
                ('noti_asunto', models.CharField(max_length=50, verbose_name='Asunto')),
                ('noti_descripcion', models.CharField(max_length=200, verbose_name='Descripcion')),
            ],
        ),
    ]
