# Generated by Django 4.2.7 on 2023-11-20 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0053_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='fk_noti_empl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asoron.empleado', verbose_name='Empleado'),
        ),
    ]
