# Generated by Django 4.2.7 on 2023-11-20 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0054_notificacion_fk_noti_empl'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacion',
            options={'verbose_name_plural': 'Notificacion'},
        ),
    ]
