# Generated by Django 4.2.7 on 2023-11-20 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0055_alter_notificacion_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaContacto',
            fields=[
                ('pers_cont_id', models.AutoField(primary_key=True, serialize=False)),
                ('pers_cont_nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('pers_cont_apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('fk_pers_cont_clie_juri', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asoron.clientejuridico')),
                ('fk_pers_cont_prov', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asoron.proveedor')),
            ],
            options={
                'verbose_name_plural': 'Persona de Contacto',
            },
        ),
        migrations.AddField(
            model_name='telefono',
            name='fk_telf_pers_cont',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pers_cont_telf', to='asoron.personacontacto'),
        ),
    ]
