# Generated by Django 4.2.7 on 2023-12-02 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0056_personacontacto_telefono_fk_telf_pers_cont'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('cargo_id', models.AutoField(primary_key=True, serialize=False, verbose_name='identificador')),
                ('cargo_nombre', models.CharField(max_length=50, verbose_name='Cargo')),
            ],
            options={
                'verbose_name_plural': 'Cargo',
            },
        ),
        migrations.CreateModel(
            name='CargoEmpleado',
            fields=[
                ('cargo_empl_id', models.AutoField(primary_key=True, serialize=False)),
                ('cargo_empl_fecha_incio', models.DateField(verbose_name='Fecha de inicio')),
                ('cargo_empl_fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('cargo_empl_salario', models.PositiveIntegerField(default=0, verbose_name='Salario')),
                ('fk_cargo_empl_empl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asoron.empleado', verbose_name='Empleado')),
                ('fk_cargo_empl_sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asoron.cargo', verbose_name='Cargo')),
            ],
        ),
        migrations.RemoveField(
            model_name='salarioempleado',
            name='fk_sala_empl_empl',
        ),
        migrations.RemoveField(
            model_name='salarioempleado',
            name='fk_sala_empl_sala',
        ),
        migrations.DeleteModel(
            name='Salario',
        ),
        migrations.DeleteModel(
            name='SalarioEmpleado',
        ),
    ]
