# Generated by Django 4.2.7 on 2023-12-02 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0057_cargo_cargoempleado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='empl_apellido_segundo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Segundo Apellido'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='empl_nombre_segundo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Segundo Nombre'),
        ),
    ]
