# Generated by Django 4.2.7 on 2023-12-02 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0058_empleado_empl_apellido_segundo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='asis_fecha',
            field=models.DateField(default='2023-12-01', verbose_name='Fecha'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='fk_empl_asis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='asoron.asistencia', verbose_name='Asistencia'),
        ),
        migrations.DeleteModel(
            name='AsistenciaEmpleado',
        ),
    ]
