# Generated by Django 4.2.7 on 2023-12-02 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0063_alter_asistencia_fk_asis_empl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='fk_asis_empl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asoron.empleado', verbose_name='Empleado'),
        ),
    ]
