# Generated by Django 4.2.7 on 2023-12-02 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0065_alter_correoelectronico_fk_mail_prov'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correoelectronico',
            name='fk_mail_prov',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='asoron.proveedor', verbose_name='Proveedor'),
        ),
    ]
