# Generated by Django 4.2.7 on 2023-12-05 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0066_alter_correoelectronico_fk_mail_prov'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ron',
            name='ron_descripcion',
            field=models.CharField(max_length=1000, verbose_name='Descripcion'),
        ),
    ]
