# Generated by Django 4.2.7 on 2023-12-05 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0067_alter_ron_ron_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ron',
            name='fk_ron_lugar',
            field=models.ForeignKey(limit_choices_to={'lugar_tipo': 'Parroquia'}, on_delete=django.db.models.deletion.CASCADE, related_name='ron_lugar', to='asoron.lugar', verbose_name='Origen'),
        ),
    ]
