# Generated by Django 4.2.7 on 2023-12-05 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0068_alter_ron_fk_ron_lugar'),
    ]

    operations = [
        migrations.CreateModel(
            name='CataEventoPremioRon',
            fields=[
                ('cata_even_premio_ron_id', models.AutoField(primary_key=True, serialize=False, verbose_name='identificador')),
                ('cata_even_premio_ron_fecha_premiacion', models.DateTimeField(verbose_name='Fecha de premiacion')),
            ],
        ),
        migrations.CreateModel(
            name='Premio',
            fields=[
                ('prem_id', models.AutoField(primary_key=True, serialize=False, verbose_name='identificador')),
                ('prem_nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('prem_descripcion', models.CharField(max_length=200, verbose_name='Descripcion')),
                ('prem_direccion', models.CharField(max_length=200, verbose_name='Direccion Fisica')),
                ('fk_prem_lugar', models.ForeignKey(limit_choices_to={'lugar_tipo': 'Parroquia'}, on_delete=django.db.models.deletion.CASCADE, to='asoron.lugar', verbose_name='Direccion')),
            ],
        ),
        migrations.CreateModel(
            name='NotaCata',
            fields=[
                ('nota_cata_id', models.AutoField(primary_key=True, serialize=False, verbose_name='identificador')),
                ('nota_cata_nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('nota_cata_descripcion', models.CharField(max_length=200, verbose_name='Descripcion')),
                ('fk_nota_cata_cata_even_premio_ron', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='asoron.cataeventopremioron', verbose_name='Cata Evento Premio Ron')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False, verbose_name='identificador')),
                ('event_nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('event_descripcion', models.CharField(max_length=200, verbose_name='Descripcion')),
                ('event_direccion', models.CharField(max_length=200, verbose_name='Direccion Fisica')),
                ('event_fecha_ini', models.DateField(verbose_name='Fecha Inicio')),
                ('event_fecha_fin', models.DateField(verbose_name='Fecha Fin')),
                ('fk_event_lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asoron.lugar', verbose_name='Direccion')),
            ],
        ),
        migrations.AddField(
            model_name='cataeventopremioron',
            name='fk_cata_even_premio_ron_evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asoron.evento', verbose_name='Evento'),
        ),
        migrations.AddField(
            model_name='cataeventopremioron',
            name='fk_cata_even_premio_ron_premio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asoron.premio', verbose_name='Premio'),
        ),
        migrations.AddField(
            model_name='cataeventopremioron',
            name='fk_cata_even_premio_ron_ron',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asoron.ron', verbose_name='Ron'),
        ),
        migrations.AlterUniqueTogether(
            name='cataeventopremioron',
            unique_together={('fk_cata_even_premio_ron_ron', 'fk_cata_even_premio_ron_premio', 'fk_cata_even_premio_ron_evento')},
        ),
    ]
