# Generated by Django 4.2.7 on 2023-12-05 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0069_cataeventopremioron_premio_notacata_evento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cataeventopremioron',
            options={'verbose_name_plural': 'Cata Evento Premio Ron'},
        ),
        migrations.AlterModelOptions(
            name='evento',
            options={'verbose_name_plural': 'Evento'},
        ),
        migrations.AlterModelOptions(
            name='notacata',
            options={'verbose_name_plural': 'Nota de Cata'},
        ),
        migrations.AlterModelOptions(
            name='premio',
            options={'verbose_name_plural': 'Premio'},
        ),
    ]
