# Generated by Django 4.2.7 on 2023-12-05 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0070_alter_cataeventopremioron_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen',
            name='fk_img_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_images', to='asoron.evento'),
        ),
    ]
