# Generated by Django 4.2.7 on 2023-12-05 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0071_imagen_fk_img_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='fk_img_ron',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ron_images', to='asoron.ron'),
        ),
    ]
