# Generated by Django 4.2.7 on 2023-12-06 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0072_alter_imagen_fk_img_ron'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notacata',
            name='fk_nota_cata_cata_even_premio_ron',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nota_cata_cata_even_premio_ron', to='asoron.cataeventopremioron', verbose_name='Cata Evento Premio Ron'),
        ),
    ]
