# Generated by Django 4.2.7 on 2023-12-08 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0076_alter_cataeventopremioron_fk_cata_even_premio_ron_evento'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTienda',
            fields=[
                ('tipo_tiend_id', models.AutoField(primary_key=True, serialize=False, verbose_name='identificador')),
                ('tipo_tiend_nombre', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name_plural': 'Tipo Tienda',
            },
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('tiend_id', models.AutoField(primary_key=True, serialize=False, verbose_name='identificador')),
                ('tiend_nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('tiend_dirrecion', models.CharField(max_length=200, verbose_name='Direccion Fisica')),
                ('fk_tiend_lugar', models.ForeignKey(limit_choices_to={'lugar_tipo': 'Parroquia'}, on_delete=django.db.models.deletion.CASCADE, to='asoron.lugar', verbose_name='Direccion')),
                ('fk_tiend_tipo_tiend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asoron.tipotienda', verbose_name='Tipo de Tienda')),
            ],
            options={
                'verbose_name_plural': 'Tienda',
            },
        ),
    ]
