# Generated by Django 4.2.7 on 2023-12-08 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0077_tipotienda_tienda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda',
            name='fk_tiend_lugar',
            field=models.ForeignKey(blank=True, limit_choices_to={'lugar_tipo': 'Parroquia'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='asoron.lugar', verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='tiend_dirrecion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Direccion Fisica'),
        ),
    ]
