# Generated by Django 4.2.7 on 2023-12-08 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0078_alter_tienda_fk_tiend_lugar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioTienda',
            fields=[
                ('inve_tiend_id', models.AutoField(primary_key=True, serialize=False, verbose_name='identificador')),
                ('inve_tiend_cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('fk_inve_tiend_bote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asoron.botella', verbose_name='Botella')),
                ('fk_inve_tiend_tiend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asoron.tienda', verbose_name='Tienda')),
            ],
            options={
                'verbose_name_plural': 'Inventario Tienda',
                'unique_together': {('fk_inve_tiend_bote', 'fk_inve_tiend_tiend')},
            },
        ),
        migrations.CreateModel(
            name='HistoricoRon',
            fields=[
                ('hist_ron_id', models.AutoField(primary_key=True, serialize=False, verbose_name='identificador')),
                ('hist_ron_fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('hist_ron_fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('hist_ron_precio', models.PositiveIntegerField(verbose_name='Precio')),
                ('fk_hist_ron_inve_tiend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asoron.inventariotienda', verbose_name='Inventario Tienda')),
            ],
            options={
                'verbose_name_plural': 'Historico Ron',
            },
        ),
    ]
