# Generated by Django 4.2.7 on 2023-12-08 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0080_inventario_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario_evento',
            name='fk_inve_event_inve_tiend',
            field=models.ForeignKey(limit_choices_to={'fk_inve_tiend_tiend__fk_tiend_tipo_tiend__tipo_tiend_nombre': 'Evento'}, on_delete=django.db.models.deletion.CASCADE, to='asoron.inventariotienda', verbose_name='Inventario Tienda'),
        ),
    ]
