# Generated by Django 4.2.7 on 2023-12-08 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0082_rename_inventario_evento_inventarioevento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventarioevento',
            name='inve_event_cantidad',
        ),
    ]
