# Generated by Django 4.2.7 on 2023-12-08 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0083_remove_inventarioevento_inve_event_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botella',
            name='fk_bote_ron',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bote_ron', to='asoron.ron', verbose_name='Ron'),
        ),
    ]
