# Generated by Django 4.2.7 on 2023-12-08 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0084_alter_botella_fk_bote_ron'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen',
            name='fk_img_bote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bote_images', to='asoron.botella'),
        ),
    ]
