# Generated by Django 4.2.7 on 2023-12-08 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0085_imagen_fk_img_bote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagen',
            name='fk_img_ron',
        ),
    ]
