# Generated by Django 5.0 on 2023-12-10 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0086_remove_imagen_fk_img_ron'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fk_event_lugar',
            field=models.ForeignKey(limit_choices_to={'lugar_tipo': 'Parroquia'}, on_delete=django.db.models.deletion.CASCADE, to='asoron.lugar', verbose_name='Direccion'),
        ),
    ]
