# Generated by Django 5.0 on 2023-12-10 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0087_alter_evento_fk_event_lugar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('ofer_id', models.AutoField(primary_key=True, serialize=False, verbose_name='identificador')),
                ('ofer_nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('ofer_descripcion', models.CharField(max_length=200, verbose_name='Descripcion')),
                ('ofer_fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('ofer_fecha_fin', models.DateField(verbose_name='Fecha de fin')),
            ],
            options={
                'verbose_name_plural': 'Oferta',
            },
        ),
        migrations.CreateModel(
            name='OfertaBotella',
            fields=[
                ('ofer_bote_id', models.AutoField(primary_key=True, serialize=False)),
                ('ofer_bote_precio', models.PositiveIntegerField(verbose_name='Precio')),
                ('fk_ofer_bote_bote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asoron.botella', verbose_name='Botella')),
                ('fk_ofer_bote_ofer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asoron.oferta', verbose_name='Oferta')),
            ],
            options={
                'verbose_name_plural': 'Oferta Botella',
                'unique_together': {('fk_ofer_bote_bote', 'fk_ofer_bote_ofer')},
            },
        ),
    ]
