# Generated by Django 5.0 on 2023-12-10 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0088_oferta_ofertabotella'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ofertabotella',
            name='ofer_bote_precio',
        ),
        migrations.AddField(
            model_name='ofertabotella',
            name='ofer_bote_porcentaje',
            field=models.PositiveIntegerField(default=15, verbose_name='Porcentaje'),
            preserve_default=False,
        ),
    ]
