# Generated by Django 5.0 on 2023-12-11 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0089_remove_ofertabotella_ofer_bote_precio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpleadoTienda',
            fields=[
                ('empl_tiend_id', models.AutoField(primary_key=True, serialize=False)),
                ('empl_tiend_fecha_incio', models.DateField(verbose_name='Fecha de inicio')),
                ('empl_tiend_fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('fk_empl_tiend_empl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asoron.empleado', verbose_name='Empleado')),
                ('fk_empl_tiend_tiend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asoron.tienda', verbose_name='Tienda')),
            ],
            options={
                'verbose_name_plural': 'Empleado Tienda',
            },
        ),
    ]
