# Generated by Django 5.0 on 2023-12-11 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0090_empleadotienda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleadotienda',
            name='fk_empl_tiend_empl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empl_tiend_empl', to='asoron.empleado', verbose_name='Empleado'),
        ),
    ]
