# Generated by Django 5.0 on 2023-12-12 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0091_alter_empleadotienda_fk_empl_tiend_empl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleadotienda',
            name='fk_empl_tiend_tiend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empl_tiend_tiend', to='asoron.tienda', verbose_name='Tienda'),
        ),
    ]
