# Generated by Django 4.2.8 on 2023-12-14 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0092_alter_empleadotienda_fk_empl_tiend_tiend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientejuridico',
            name='fk_clie_juri_lugar_fiscal',
            field=models.ForeignKey(limit_choices_to={'lugar_tipo': 'parroquia'}, on_delete=django.db.models.deletion.PROTECT, related_name='clie_juri_lugar_fiscal', to='asoron.lugar', verbose_name='Direccion Fiscal Geografica'),
        ),
        migrations.AlterField(
            model_name='clientejuridico',
            name='fk_clie_juri_lugar_fisica',
            field=models.ForeignKey(limit_choices_to={'lugar_tipo': 'parroquia'}, on_delete=django.db.models.deletion.PROTECT, to='asoron.lugar', verbose_name='Direccion Fisica Geografica'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fk_event_lugar',
            field=models.ForeignKey(limit_choices_to={'lugar_tipo': 'parroquia'}, on_delete=django.db.models.deletion.CASCADE, to='asoron.lugar', verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='lugar_tipo',
            field=models.CharField(choices=[('pais', 'pais'), ('municipio', 'municipio'), ('estado', 'estado'), ('parroquia', 'parroquia')], max_length=50, verbose_name='Tipo de lugar'),
        ),
        migrations.AlterField(
            model_name='premio',
            name='fk_prem_lugar',
            field=models.ForeignKey(limit_choices_to={'lugar_tipo': 'parroquia'}, on_delete=django.db.models.deletion.CASCADE, to='asoron.lugar', verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='ron',
            name='fk_ron_lugar',
            field=models.ForeignKey(limit_choices_to={'lugar_tipo': 'parroquia'}, on_delete=django.db.models.deletion.CASCADE, related_name='ron_lugar', to='asoron.lugar', verbose_name='Origen'),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='fk_tiend_lugar',
            field=models.ForeignKey(blank=True, limit_choices_to={'lugar_tipo': 'parroquia'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='asoron.lugar', verbose_name='Direccion'),
        ),
    ]
