# Generated by Django 4.2.8 on 2023-12-14 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0094_alter_clientenatural_fk_clie_natu_lugar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='fk_empl_lugar',
            field=models.ForeignKey(limit_choices_to={'lugar_tipo': 'parroquia'}, on_delete=django.db.models.deletion.PROTECT, to='asoron.lugar', verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='fk_prov_lugar',
            field=models.ForeignKey(limit_choices_to={'lugar_tipo': 'parroquia'}, on_delete=django.db.models.deletion.PROTECT, to='asoron.lugar', verbose_name='Direccion'),
        ),
    ]
