# Generated by Django 4.2.8 on 2023-12-15 22:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0095_alter_empleado_fk_empl_lugar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoron',
            name='hist_ron_precio',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1.0)], verbose_name='Precio'),
        ),
    ]
