# Generated by Django 4.2.8 on 2023-12-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0096_alter_historicoron_hist_ron_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='event_descripcion',
            field=models.CharField(max_length=1000, verbose_name='Descripcion'),
        ),
    ]
