# Generated by Django 4.2.8 on 2023-12-17 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0097_alter_evento_event_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='fk_event_tien',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asoron.tienda', verbose_name='Tienda'),
        ),
        migrations.DeleteModel(
            name='InventarioEvento',
        ),
    ]
