# Generated by Django 4.2.8 on 2023-12-18 22:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0100_alter_evento_fk_event_tien'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaEvento',
            fields=[
                ('entr_envt_id', models.AutoField(primary_key=True, serialize=False)),
                ('entr_envt_nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('entr_envt_fecha_inicio', models.DateTimeField(verbose_name='Fecha')),
                ('entr_envt_fecha_fin', models.DateTimeField(verbose_name='Fecha de fin')),
                ('entr_envt_precio', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0)], verbose_name='Precio')),
                ('fk_entr_envt_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asoron.evento', verbose_name='Evento')),
            ],
            options={
                'verbose_name_plural': 'Entrada Evento',
            },
        ),
    ]
