# Generated by Django 4.2.8 on 2023-12-18 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0103_alter_entradaevento_entr_evnt_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradaevento',
            name='fk_entr_envt_evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entr_envt_evento', to='asoron.evento', verbose_name='Evento'),
        ),
    ]
