# Generated by Django 4.2.8 on 2023-12-18 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0104_alter_entradaevento_fk_entr_envt_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradaevento',
            name='entr_envt_descripcion',
            field=models.CharField(default=' ', max_length=200, verbose_name='Descripcion'),
        ),
    ]
