# Generated by Django 4.2.8 on 2023-12-19 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0105_entradaevento_entr_envt_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientenatural',
            name='clie_natu_cedula_identidad',
            field=models.CharField(max_length=10, unique=True, verbose_name='Cedula de identidad'),
        ),
        migrations.AlterField(
            model_name='clientenatural',
            name='clie_natu_rif',
            field=models.CharField(max_length=10, unique=True, verbose_name='RIF'),
        ),
    ]
