# Generated by Django 4.2.8 on 2023-12-19 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0107_alter_clientejuridico_clie_juri_rif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='empl_cedula_identidad',
            field=models.CharField(max_length=10, unique=True, verbose_name='Cedula de identidad'),
        ),
    ]
