# Generated by Django 4.2.8 on 2023-12-22 02:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0108_alter_empleado_empl_cedula_identidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('compr_id', models.AutoField(primary_key=True, serialize=False, verbose_name='identificador')),
                ('compr_fecha_compra', models.DateTimeField(verbose_name='Fecha de compra')),
                ('compr_tiend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asoron.tienda', verbose_name='Tienda')),
            ],
            options={
                'verbose_name_plural': 'Compra',
            },
        ),
        migrations.CreateModel(
            name='StatusPedido',
            fields=[
                ('stat_pedi_id', models.AutoField(primary_key=True, serialize=False, verbose_name='identificador')),
                ('stat_pedi_nombre', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name_plural': 'Status Pedido',
            },
        ),
        migrations.CreateModel(
            name='VentaStatus',
            fields=[
                ('venta_stat_id', models.AutoField(primary_key=True, serialize=False, verbose_name='identificador')),
                ('venta_stat_status', models.BooleanField(verbose_name='Comprobante')),
                ('venta_stat_fecha_inicio', models.DateTimeField(verbose_name='Fecha antes de comprobacion')),
                ('venta_stat_fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha despues de comprobacion')),
                ('venta_stat_compr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asoron.compra', verbose_name='Compra')),
                ('venta_stat_stat_pedi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asoron.statuspedido', verbose_name='Status Pedido')),
            ],
            options={
                'verbose_name_plural': 'Status Venta',
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('deta_compr_id', models.AutoField(primary_key=True, serialize=False, verbose_name='identificador')),
                ('deta_compr_cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('deta_compr_precio', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0)], verbose_name='Precio')),
                ('fk_deta_compr_bote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asoron.botella', verbose_name='Botella')),
                ('fk_deta_compr_compr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asoron.compra', verbose_name='Compra')),
            ],
            options={
                'verbose_name_plural': 'Detalle Compra',
                'unique_together': {('fk_deta_compr_compr', 'fk_deta_compr_bote')},
            },
        ),
    ]
