# Generated by Django 4.2.8 on 2023-12-22 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0109_compra_statuspedido_ventastatus_detallecompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='compr_prove',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='asoron.proveedor', verbose_name='Proveedor'),
        ),
    ]
