# Generated by Django 4.2.8 on 2023-12-22 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0110_compra_compr_prove'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='compr_prove',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asoron.proveedor', verbose_name='Proveedor'),
        ),
    ]
