# Generated by Django 4.2.8 on 2023-12-25 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0112_rename_compr_prove_compra_fk_compr_prove_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Afiliado',
            fields=[
                ('afil_id', models.AutoField(primary_key=True, serialize=False, verbose_name='identificador')),
                ('afil_nombre', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name_plural': 'Afiliado',
            },
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('carr_id', models.AutoField(primary_key=True, serialize=False, verbose_name='identificador')),
                ('fk_carr_clie_juri', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asoron.clientejuridico', verbose_name='Cliente Juridico')),
                ('fk_carr_clie_natu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asoron.clientenatural', verbose_name='Cliente Natural')),
            ],
            options={
                'verbose_name_plural': 'Carrito',
            },
        ),
        migrations.CreateModel(
            name='AfiliadoClienteProveedor',
            fields=[
                ('afil_clie_prov_id', models.AutoField(primary_key=True, serialize=False, verbose_name='identificador')),
                ('afil_clie_prov_fecha_afiliacion', models.DateField(verbose_name='Fecha de afiliacion')),
                ('afil_clie_prov_fecha_vencimiento', models.DateField(verbose_name='Fecha de vencimiento')),
                ('fk_afil_clie_prov_afil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asoron.afiliado', verbose_name='Afiliado')),
                ('fk_afil_clie_prov_clie_juri', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asoron.clientejuridico', verbose_name='Cliente Juridico')),
                ('fk_afil_clie_prov_clie_natu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asoron.clientenatural', verbose_name='Cliente Natural')),
                ('fk_afil_clie_prov_prov', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asoron.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name_plural': 'Afiliado Cliente Proveedor',
            },
        ),
        migrations.CreateModel(
            name='CarritoItem',
            fields=[
                ('carri_item_id', models.AutoField(primary_key=True, serialize=False, verbose_name='identificador')),
                ('carri_item_cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('fk_carri_item_afil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asoron.afiliado', verbose_name='Afiliado')),
                ('fk_carri_item_carri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asoron.carrito', verbose_name='Carrito')),
                ('fk_carri_item_entr_evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asoron.entradaevento', verbose_name='Entrada Evento')),
                ('fk_carri_item_inve_tiend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asoron.inventariotienda', verbose_name='Inventario Tienda')),
                ('fk_carri_item_ofer_ron', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asoron.ofertabotella', verbose_name='Oferta Botella')),
            ],
            options={
                'verbose_name_plural': 'Carrito Item',
                'unique_together': {('fk_carri_item_carri', 'fk_carri_item_inve_tiend', 'fk_carri_item_ofer_ron', 'fk_carri_item_entr_evento', 'fk_carri_item_afil')},
            },
        ),
    ]
