# Generated by Django 4.2.8 on 2023-12-25 21:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0113_afiliado_carrito_afiliadoclienteproveedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='afiliado',
            name='afil_precio',
            field=models.FloatField(default=10, validators=[django.core.validators.MinValueValidator(1.0)], verbose_name='Precio'),
            preserve_default=False,
        ),
    ]
