# Generated by Django 4.2.8 on 2023-12-25 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0114_afiliado_afil_precio'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carritoitem',
            unique_together={('fk_carri_item_carri', 'fk_carri_item_afil')},
        ),
    ]
