# Generated by Django 4.2.8 on 2023-12-25 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0115_alter_carritoitem_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carritoitem',
            unique_together={('fk_carri_item_carri', 'fk_carri_item_entr_evento'), ('fk_carri_item_carri', 'fk_carri_item_inve_tiend', 'fk_carri_item_ofer_ron'), ('fk_carri_item_carri', 'fk_carri_item_inve_tiend'), ('fk_carri_item_carri', 'fk_carri_item_afil')},
        ),
    ]
