# Generated by Django 4.2.8 on 2023-12-25 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0116_alter_carritoitem_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritoitem',
            name='fk_carri_item_inve_tiend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asoron.inventariotienda', verbose_name='Inventario Tienda'),
        ),
    ]
