# Generated by Django 4.2.8 on 2023-12-26 22:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0117_alter_carritoitem_fk_carri_item_inve_tiend'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoDolar',
            fields=[
                ('hist_dolar_id', models.AutoField(primary_key=True, serialize=False, verbose_name='identificador')),
                ('hist_dolar_valor', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0)], verbose_name='Valor')),
                ('hist_folar_fecha_inicio', models.DateTimeField(verbose_name='Fecha de inicio')),
                ('hist_folar_fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de fin')),
            ],
            options={
                'verbose_name_plural': 'Historico Dolar',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('vent_id', models.AutoField(primary_key=True, serialize=False, verbose_name='identificador')),
                ('vent_fecha_venta', models.DateTimeField(verbose_name='Fecha de venta')),
                ('vent_monto_total', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0)], verbose_name='Precio')),
                ('venta_puntos', models.PositiveIntegerField(default=0, verbose_name='Puntos')),
                ('venta_direccion', models.CharField(max_length=200, verbose_name='Direccion Fisica')),
                ('fk_vent_carri', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='asoron.carrito', verbose_name='Carrito')),
                ('fk_vent_direccion', models.ForeignKey(limit_choices_to={'lugar_tipo': 'parroquia'}, on_delete=django.db.models.deletion.CASCADE, to='asoron.lugar', verbose_name='Direccion')),
                ('fk_vent_empl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asoron.empleado', verbose_name='Empleado')),
            ],
            options={
                'verbose_name_plural': 'Venta',
            },
        ),
        migrations.AddField(
            model_name='ventastatus',
            name='fk_venta_stat_vent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asoron.venta', verbose_name='Venta'),
        ),
    ]
