# Generated by Django 4.2.8 on 2023-12-26 22:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0119_cheque_efectivo_tarjetacredito_puntos_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoPunto',
            fields=[
                ('hist_punt_id', models.AutoField(primary_key=True, serialize=False, verbose_name='identificador')),
                ('hist_punt_valor', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0)], verbose_name='Valor')),
                ('hist_punt_fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('hist_punt_fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
            ],
            options={
                'verbose_name_plural': 'Historico Punto',
            },
        ),
        migrations.AddField(
            model_name='pago',
            name='fk_pago_hist_punt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asoron.historicopunto', verbose_name='Historico Punto'),
        ),
    ]
