# Generated by Django 4.2.8 on 2023-12-26 22:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0120_historicopunto_pago_fk_pago_hist_punt'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='carr_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
    ]
