# Generated by Django 4.2.8 on 2023-12-26 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0121_carrito_carr_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puntos',
            name='punt_cantidad',
        ),
    ]
