# Generated by Django 4.2.8 on 2023-12-26 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0122_remove_puntos_punt_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntos',
            name='punt_tiene_puntos',
            field=models.BooleanField(default=False, verbose_name='Tiene puntos'),
            preserve_default=False,
        ),
    ]
