# Generated by Django 4.2.8 on 2023-12-26 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0123_puntos_punt_tiene_puntos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicodolar',
            old_name='hist_folar_fecha_fin',
            new_name='hist_dolar_fecha_fin',
        ),
        migrations.RenameField(
            model_name='historicodolar',
            old_name='hist_folar_fecha_inicio',
            new_name='hist_dolar_fecha_inicio',
        ),
    ]
