# Generated by Django 4.2.8 on 2023-12-26 23:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0124_rename_hist_folar_fecha_fin_historicodolar_hist_dolar_fecha_fin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AfiliadoCodigo',
            fields=[
                ('afil_codigo_id', models.AutoField(primary_key=True, serialize=False, verbose_name='identificador')),
                ('afil_codigo_codigo', models.CharField(max_length=8, unique=True, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='Codigo')),
            ],
        ),
        migrations.AddField(
            model_name='clientejuridico',
            name='fk_clie_juri_afil_codigo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='asoron.afiliadocodigo', verbose_name='Afiliado Codigo'),
        ),
        migrations.AddField(
            model_name='clientenatural',
            name='fk_clie_natu_afil_codigo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='asoron.afiliadocodigo', verbose_name='Afiliado Codigo'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='fk_prov_afil_codigo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='asoron.afiliadocodigo', verbose_name='Afiliado Codigo'),
        ),
    ]
