# Generated by Django 4.2.8 on 2023-12-27 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0127_remove_clientejuridico_unique_afiliado_codigo_cliente_juridico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientejuridico',
            name='fk_clie_juri_afil_codigo',
        ),
        migrations.RemoveField(
            model_name='clientenatural',
            name='fk_clie_natu_afil_codigo',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='fk_prov_afil_codigo',
        ),
    ]
