# Generated by Django 4.2.8 on 2023-12-27 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0128_remove_clientejuridico_fk_clie_juri_afil_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='afiliadocodigo',
            name='fk_afil_clie_juri',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asoron.clientejuridico', verbose_name='Cliente Juridico'),
        ),
        migrations.AddField(
            model_name='afiliadocodigo',
            name='fk_afil_clie_natu',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asoron.clientenatural', verbose_name='Cliente Natural'),
        ),
        migrations.AddField(
            model_name='afiliadocodigo',
            name='fk_afil_prov',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asoron.proveedor', verbose_name='Proveedor'),
        ),
    ]
