# Generated by Django 4.2.8 on 2023-12-27 18:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0129_afiliadocodigo_fk_afil_clie_juri_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afiliadocodigo',
            name='afil_codigo_codigo',
            field=models.CharField(editable=False, max_length=8, unique=True, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='Codigo'),
        ),
    ]
