# Generated by Django 4.2.8 on 2023-12-27 18:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0130_alter_afiliadocodigo_afil_codigo_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afiliadocodigo',
            name='afil_codigo_codigo',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='Codigo'),
        ),
    ]
