# Generated by Django 4.2.8 on 2023-12-29 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0131_alter_afiliadocodigo_afil_codigo_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarritoViewSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='carrito',
            name='carri_comprado',
            field=models.BooleanField(default=False, verbose_name='Comprado'),
        ),
    ]
