# Generated by Django 4.2.8 on 2023-12-29 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0132_carritoviewset_carrito_carri_comprado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarritoViewSet',
        ),
    ]
