# Generated by Django 4.2.8 on 2023-12-29 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0133_delete_carritoviewset'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='carri_empleado',
            field=models.BooleanField(default=False, verbose_name='Empleado'),
        ),
    ]
