# Generated by Django 4.2.8 on 2024-01-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0134_carrito_carri_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheque',
            name='chq_nombre_titular',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Nombre del titular'),
        ),
    ]
