# Generated by Django 4.2.8 on 2024-01-02 13:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0135_cheque_chq_nombre_titular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicopunto',
            name='hist_punt_valor',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Valor'),
        ),
    ]
