# Generated by Django 4.2.8 on 2024-01-02 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0136_alter_historicopunto_hist_punt_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='pago_tipo_pago',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de pago'),
        ),
    ]
