# Generated by Django 4.2.8 on 2024-01-02 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0137_pago_pago_tipo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritoitem',
            name='carri_item_precio',
            field=models.FloatField(default=10, verbose_name='Precio'),
            preserve_default=False,
        ),
    ]
