# Generated by Django 4.2.8 on 2024-01-04 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0138_carritoitem_carri_item_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='fk_vent_empl',
        ),
        migrations.AddField(
            model_name='carrito',
            name='fk_carr_clie_emples',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asoron.empleado', verbose_name='Empleado'),
        ),
    ]
