# Generated by Django 4.2.8 on 2024-01-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0140_alter_notificacion_noti_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='noti_id_prov',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='noti_id_tienda',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Tienda'),
        ),
    ]
