# Generated by Django 4.2.8 on 2024-01-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0141_notificacion_noti_id_prov_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='noti_id_prov',
            field=models.PositiveIntegerField(verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='noti_id_tienda',
            field=models.PositiveIntegerField(verbose_name='Tienda'),
        ),
    ]
