# Generated by Django 4.2.8 on 2024-01-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0142_alter_notificacion_noti_id_prov_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='noti_id_pro',
            field=models.PositiveIntegerField(default=0, verbose_name='Producto'),
        ),
    ]
