# Generated by Django 4.2.8 on 2024-01-06 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0143_notificacion_noti_id_pro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientejuridico',
            name='clie_juri_puntos',
            field=models.FloatField(default=0, verbose_name='Puntos'),
        ),
        migrations.AlterField(
            model_name='clientenatural',
            name='clie_natu_puntos',
            field=models.FloatField(default=0, verbose_name='Puntos'),
        ),
    ]
