# Generated by Django 4.2.7 on 2023-11-10 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0013_materiaprima_materiaprimaron'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fk_usua_empl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_usua_empl', to='asoron.empleado'),
        ),
    ]
