# Generated by Django 4.2.7 on 2023-11-12 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asoron', '0030_prueba'),
        ('core', '0005_alter_usuario_fk_usua_empl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fk_usua_empl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asoron.empleado'),
        ),
    ]
